### ISSUE TITLE
"exports is not defined in ES module scope"

### ISSUE THREAD

**Issue by oakleaf** [lumigo-io/lumigo-node#376]
**Describe the bug**
Trying to use Lumigo/Tracer as module in a nodejs14 setup with Lambda. Since my Lambda function is 'module enabled', it can't use "require"- hence the Lumigo-layer throws me errors about using 'require'.

**To Reproduce**
1) Use Lambda layer or install the package locally
2) Try to import the package in your function 
import Lumigo from "@lumigo/tracer";
3) Run your function

**Expected behavior**
Being able to use the module and Lumigo application

**Runtime details**
Node14

**Errors**
```
{
  "errorType": "ReferenceError",
  "errorMessage": "exports is not defined in ES module scope\nThis file is being treated as an ES module because it has a '.js' file extension and '/var/task/package.json' contains \"type\": \"module\". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.",
  "trace": [
    "ReferenceError: exports is not defined in ES module scope",
    "This file is being treated as an ES module because it has a '.js' file extension and '/var/task/package.json' contains \"type\": \"module\". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.",
    "    at file:///var/task/index.js:180:1",
    "    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)",
    "    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:60:5)",
    "    at /var/runtime/deasync.js:23:15",
    "    at _tryAwaitImport (/var/runtime/UserFunction.js:74:12)",
    "    at _tryRequire (/var/runtime/UserFunction.js:162:21)",
    "    at _loadUserApp (/var/runtime/UserFunction.js:197:12)",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:242:17)",
    "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:1085:14)"
  ]
}
```

**Comment by doriaviram** [comment]
Hey @oakleaf, we checking it out

**Comment by doriaviram** [comment]
Hey @oakleaf `"type": "module"` in the client package.json didnt help us to reproduce the problem, can you share more details about your package?

**Comment by doriaviram** [comment]
@oakleaf 
We can add `let exports = {}` that probably will solve the problem, we just want to reproduce that first

**Comment by oakleaf** [comment]
In my package.js i have "type": "module", so I can use "import" instead of ```const lumigo = require(...)```, this together with NodeJS14 in Lambda (AWS).

At the top of my index.js-file (my handler):
```import lumigo from "@lumigo/tracer";``` 

This exactly gives me the error;

`{
  "errorType": "ReferenceError",
  "errorMessage": "exports is not defined in ES module scope\nThis file is being treated as an ES module because it has a '.js' file extension and '/var/task/package.json' contains \"type\": \"module\". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.",
  "trace": [
    "ReferenceError: exports is not defined in ES module scope",
    "This file is being treated as an ES module because it has a '.js' file extension and '/var/task/package.json' contains \"type\": \"module\". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.",
    "    at file:///var/task/index.js:179:1",
    "    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)",
    "    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:60:5)",
    "    at /var/runtime/deasync.js:23:15",
    "    at _tryAwaitImport (/var/runtime/UserFunction.js:74:12)",
    "    at _tryRequire (/var/runtime/UserFunction.js:162:21)",
    "    at _loadUserApp (/var/runtime/UserFunction.js:197:12)",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:242:17)",
    "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:1085:14)"
  ]
}`

And as you can see in the error message, it complains about exports not being defined. All my own classes and modules has "exportations" in each document, eg: ```export default class Image```

Maybe you need to enable nodejs14 in your build? [https://github.com/lumigo-io/lumigo-node/blob/master/package.json](https://github.com/lumigo-io/lumigo-node/blob/master/package.json) says nothing about nodejs14 in the description (I get it, it's probably not just updated yet)

I also use this module, [https://github.com/lovell/sharp](https://github.com/lovell/sharp) which works fine, maybe they have some configurations going for them?

**Comment by oakleaf** [comment]
It works! I get why this bothered me, in your READMORE, in the section about TS;

`// typescript
import lumigo from '@lumigo/tracer';

const myHandler = async (event, context, callback) => { ... }

exports.handler = lumigo({ token: 'YOUR-TOKEN-HERE' }).trace(myHandler)`

It threw me off, because I also wrote ```exports.handler = lumigo({ token: 'YOUR-TOKEN-HERE' }).trace(myHandler)```

But in your example above, you wrote (the correct way of exporting) ```export konst handler = ...``` and that was the reason of the error!

Thanks guys!

**Comment by doriaviram** [comment]
@oakleaf Thanks, we will update the readme
